// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/s-turchinskiy/keeper/internal/client/repository (interfaces: Repositorier)

// Package mocksclientrepository is a generated GoMock package.
package mocksclientrepository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/s-turchinskiy/keeper/internal/client/models"
)

// MockRepositorier is a mock of Repositorier interface.
type MockRepositorier struct {
	ctrl     *gomock.Controller
	recorder *MockRepositorierMockRecorder
}

// MockRepositorierMockRecorder is the mock recorder for MockRepositorier.
type MockRepositorierMockRecorder struct {
	mock *MockRepositorier
}

// NewMockRepositorier creates a new mock instance.
func NewMockRepositorier(ctrl *gomock.Controller) *MockRepositorier {
	mock := &MockRepositorier{ctrl: ctrl}
	mock.recorder = &MockRepositorierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositorier) EXPECT() *MockRepositorierMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRepositorier) Close(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRepositorierMockRecorder) Close(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRepositorier)(nil).Close), arg0)
}

// Create mocks base method.
func (m *MockRepositorier) Create(arg0 context.Context, arg1 *models.LocalSecret) (*models.LocalSecret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*models.LocalSecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositorierMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepositorier)(nil).Create), arg0, arg1)
}

// DeleteByKey mocks base method.
func (m *MockRepositorier) DeleteByKey(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByKey", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByKey indicates an expected call of DeleteByKey.
func (mr *MockRepositorierMockRecorder) DeleteByKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByKey", reflect.TypeOf((*MockRepositorier)(nil).DeleteByKey), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockRepositorier) GetAll(arg0 context.Context) ([]*models.LocalSecret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]*models.LocalSecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRepositorierMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRepositorier)(nil).GetAll), arg0)
}

// GetByKey mocks base method.
func (m *MockRepositorier) GetByKey(arg0 context.Context, arg1 string) (*models.LocalSecret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKey", arg0, arg1)
	ret0, _ := ret[0].(*models.LocalSecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKey indicates an expected call of GetByKey.
func (mr *MockRepositorierMockRecorder) GetByKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKey", reflect.TypeOf((*MockRepositorier)(nil).GetByKey), arg0, arg1)
}

// UpdateByKey mocks base method.
func (m *MockRepositorier) UpdateByKey(arg0 context.Context, arg1 string, arg2 *models.LocalSecret) (*models.LocalSecret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.LocalSecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByKey indicates an expected call of UpdateByKey.
func (mr *MockRepositorierMockRecorder) UpdateByKey(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByKey", reflect.TypeOf((*MockRepositorier)(nil).UpdateByKey), arg0, arg1, arg2)
}
