// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/s-turchinskiy/keeper/internal/server/repository (interfaces: SecretRepositorier)

// Package mockserverrepository is a generated GoMock package.
package mockserverrepository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/s-turchinskiy/keeper/internal/server/models"
)

// MockSecretRepositorier is a mock of SecretRepositorier interface.
type MockSecretRepositorier struct {
	ctrl     *gomock.Controller
	recorder *MockSecretRepositorierMockRecorder
}

// MockSecretRepositorierMockRecorder is the mock recorder for MockSecretRepositorier.
type MockSecretRepositorierMockRecorder struct {
	mock *MockSecretRepositorier
}

// NewMockSecretRepositorier creates a new mock instance.
func NewMockSecretRepositorier(ctrl *gomock.Controller) *MockSecretRepositorier {
	mock := &MockSecretRepositorier{ctrl: ctrl}
	mock.recorder = &MockSecretRepositorierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretRepositorier) EXPECT() *MockSecretRepositorierMockRecorder {
	return m.recorder
}

// CreateUpdate mocks base method.
func (m *MockSecretRepositorier) CreateUpdate(arg0 context.Context, arg1 *models.Secret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUpdate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUpdate indicates an expected call of CreateUpdate.
func (mr *MockSecretRepositorierMockRecorder) CreateUpdate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUpdate", reflect.TypeOf((*MockSecretRepositorier)(nil).CreateUpdate), arg0, arg1)
}

// Delete mocks base method.
func (m *MockSecretRepositorier) Delete(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSecretRepositorierMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSecretRepositorier)(nil).Delete), arg0, arg1, arg2)
}

// GetAll mocks base method.
func (m *MockSecretRepositorier) GetAll(arg0 context.Context, arg1 string) ([]*models.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0, arg1)
	ret0, _ := ret[0].([]*models.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSecretRepositorierMockRecorder) GetAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSecretRepositorier)(nil).GetAll), arg0, arg1)
}

// GetAllWithStatuses mocks base method.
func (m *MockSecretRepositorier) GetAllWithStatuses(arg0 context.Context, arg1 string) ([]*models.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithStatuses", arg0, arg1)
	ret0, _ := ret[0].([]*models.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWithStatuses indicates an expected call of GetAllWithStatuses.
func (mr *MockSecretRepositorierMockRecorder) GetAllWithStatuses(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithStatuses", reflect.TypeOf((*MockSecretRepositorier)(nil).GetAllWithStatuses), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockSecretRepositorier) GetByID(arg0 context.Context, arg1, arg2 string) (*models.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSecretRepositorierMockRecorder) GetByID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSecretRepositorier)(nil).GetByID), arg0, arg1, arg2)
}

// TruncateAllTabs mocks base method.
func (m *MockSecretRepositorier) TruncateAllTabs(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TruncateAllTabs", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// TruncateAllTabs indicates an expected call of TruncateAllTabs.
func (mr *MockSecretRepositorierMockRecorder) TruncateAllTabs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TruncateAllTabs", reflect.TypeOf((*MockSecretRepositorier)(nil).TruncateAllTabs), arg0)
}
